services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
